Repository kaiyuanshe/OpenHackathon-Web, pull requests merged in 2022-11, with the labels that each got.

#139 [optimize] replace Activity Log with Notice List in Activity Detail page
  components/Message/MessageList.tsx
  models/Activity.ts
  models/Message.ts
  package.json
  pages/activity/[name]/index.tsx
  pages/activity/[name]/manage/message.tsx
  pnpm-lock.yaml
Labels: bug

#140 [add] manage log page
  components/Activity/ActivityManageFrame.tsx
  components/GitLogo.tsx
  locales/en-US.json
  locales/zh-Hans.json
  locales/zh-Hant-TW.json
  models/Staff.ts
  pages/_document.tsx
  pages/activity/[name]/manage/log.tsx
Labels: enhancement

#141 [add] Activity Rich-text editor
  .vscode/launch.json
  README.md
  components/Activity/ActivityList.tsx
  components/Activity/ActivityLogList.tsx
  components/Activity/GitList.tsx
  components/ActivityAdministratorModal.tsx
  components/ActivityEditor.tsx
  components/AwardList.tsx
  components/EnrollmentList.tsx
  components/Message/MessageEditor.tsx
  components/Message/MessageList.tsx
  components/Message/MessageModal.tsx
  components/Organization/ActivityOrganizationModal.tsx
  components/Organization/OrganizationList.tsx
  components/ScrollList.tsx
  components/Team/TeamAdministratorTable.tsx
  components/Team/TeamList.tsx
  components/Team/TeamMemberList.tsx
  components/Team/TeamParticipantTable.tsx
  components/Team/TeamWorkList.tsx
  components/User/LanguageMenu.tsx
  components/User/StaffList.tsx
  components/User/UserBar.tsx
  components/User/UserList.tsx
  jest-playwright.config.js
  jest.config.ts
  locales/en-US.json
  locales/zh-Hans.json
  locales/zh-Hant-TW.json
  models/Staff.ts
  models/Team.ts
  package.json
  pages/_app.tsx
  pages/_document.tsx
  pages/activity/[name]/index.tsx
  pages/activity/[name]/manage/message.tsx
  pages/activity/[name]/manage/organization.tsx
  pages/activity/[name]/register.tsx
  pages/activity/[name]/team/[tid]/index.tsx
  pages/api/core.ts
  pages/index.tsx
  pnpm-lock.yaml
  styles/globals.less
  test/home.spec.ts
  tsconfig.json
  utils/i18n.ts
Labels: feature

#135 add admin frame
  components/Activity/ActivityManageFrame.tsx
  components/PlatformAdmin/PlatformAdminFrame.tsx
  components/layout/MainNavigation.tsx
  locales/en-US.json
  locales/zh-Hans.json
  locales/zh-Hant-TW.json
  models/Activity.ts
  models/PlatformAdmin.ts
  models/Staff.ts
  package.json
  pages/admin/index.tsx
  pnpm-lock.yaml
Labels: feature

#144 feat: add platform admin
  components/Activity/ActivityList.tsx
  components/ActivityAdministratorModal.tsx
  components/PlatformAdmin/PlatformAdminList.tsx
  components/PlatformAdmin/PlatformAdminModal.tsx
  components/User/HackathonAdminList.tsx
  components/User/LanguageMenu.tsx
  components/User/StaffList.tsx
  components/User/UserBar.tsx
  components/User/UserList.tsx
  locales/en-US.json
  locales/zh-Hans.json
  locales/zh-Hant-TW.json
  models/HackathonAdmin.ts
  models/PlatformAdmin.ts
  models/Staff.ts
  pages/admin/platform-admin.tsx
Labels: feature

#145 [add] Testing RESTful API configuration
  .env
  .env.development
  .env.production
  README.md
  components/ActivityEditor.tsx
  models/Activity.ts
  models/Base.ts
  package.json
  pnpm-lock.yaml
Labels: bug

#84 2022 活动管理 团队作品评奖页
  components/AwardList.tsx
  components/Team/TeamAwardAssignment.tsx
  components/Team/TeamAwardCard.tsx
  components/Team/TeamAwardList.tsx
  components/Team/TeamWork.tsx
  locales/en-US.json
  locales/zh-Hans.json
  models/Award.ts
  models/Team.ts
  pages/activity/[name]/manage/award.tsx
  pages/activity/[name]/manage/evaluation.tsx
  styles/globals.less
Labels: feature
