Repository kaiyuanshe/OpenHackathon-Web, pull requests merged in 2022-09, with the labels that each got.

#87 [fix] Image Uploading errors of Activity Editing pages
  .github/workflows/main.yml
  .github/workflows/pull-request.yml
  README.md
  components/ActivityCreate.tsx
  components/ActivityEdit.tsx
  next.config.js
  package.json
  pages/_document.tsx
  pnpm-lock.yaml
  yarn.lock
Labels: enhancement

#90 [add] Docker configuration
  .github/workflows/docker.yml
  Dockerfile
  next.config.js
Labels: feature

#92 [refactor] replace AMap with OpenStreetMap
  .env
  components/LocationMap.tsx
  models/Map.ts
  models/User.ts
  package.json
  pages/_document.tsx
  pages/activity/[name]/index.tsx
  pages/api/rich-edit.json
  pnpm-lock.yaml
  tsconfig.json
Labels: enhancement

#91 add create Team
  components/ActivityEditor.tsx
  components/ActivityEntry.tsx
  components/TeamCard.tsx
  components/TeamCreateModal.tsx
  components/TeamEditor.tsx
  models/Enrollment.ts
  models/Team.ts
  pages/activity/[name]/index.tsx
  pages/activity/[name]/manage/award.tsx
Labels: feature

#107 [refactor] simplify most pages with Stream List models & components based on MobX RESTful
  README.md
  components/Activity/ActivityCard.tsx
  components/Activity/ActivityControl.tsx
  components/Activity/ActivityEntry.tsx
  components/Activity/ActivityList.tsx
  components/Activity/ActivityManageFrame.tsx
  components/ActivityAdministratorModal.tsx
  components/ActivityCreate.tsx
  components/ActivityEdit.tsx
  components/ActivityEditor.tsx
  components/ActivityList.tsx
  components/AwardList.tsx
  components/EnrollmentList.tsx
  components/FileUpload.tsx
  components/ScrollList.tsx
  components/Team/TeamCard.tsx
  components/Team/TeamList.tsx
  components/Team/TeamMemberList.tsx
  components/Team/TeamWorkList.tsx
  components/TeamCard.tsx
  components/TeamCreateModal.tsx
  components/TeamEditor.tsx
  components/User/AuthingGuard.tsx
  components/User/SessionBox.tsx
  components/User/StaffList.tsx
  components/User/UserBar.tsx
  components/User/UserList.tsx
  components/UserBar.tsx
  components/layout/MainNavigation.tsx
  models/Activity.ts
  models/ActivityManage.ts
  models/Award.ts
  models/Base.ts
  models/Enrollment.ts
  models/Session.ts
  models/Staff.ts
  models/Team.ts
  models/Upload.ts
  models/User.ts
  package.json
  pages/_app.tsx
  pages/_document.tsx
  pages/activity/[name]/index.tsx
  pages/activity/[name]/manage/administrator.tsx
  pages/activity/[name]/manage/award.tsx
  pages/activity/[name]/manage/edit.tsx
  pages/activity/[name]/manage/participant.tsx
  pages/activity/[name]/register.tsx
  pages/activity/[name]/team/[tid].tsx
  pages/activity/create.tsx
  pages/activity/index.tsx
  pages/admin/index.tsx
  pages/api/core.ts
  pages/api/user/session.ts
  pages/index.tsx
  pages/user/[id].tsx
  pages/user/sign-in.tsx
  pnpm-lock.yaml
  utils/uploadFile.ts
Labels: enhancement, feature
