Repository kaiyuanshe/OpenHackathon-Web, pull requests merged in 2022-10, with the labels that each got.

#110 [add] Manage page of Activity Team
  components/Activity/ActivityManageFrame.tsx
  models/Enrollment.ts
  models/Session.ts
  models/Staff.ts
  models/Team.ts
  package.json
  pages/activity/[name]/manage/participant.tsx
  pages/activity/[name]/manage/team.tsx
  pnpm-lock.yaml
Labels: enhancement

#111 [add] Comment Box component
  components/Activity/ActivityManageFrame.tsx
  components/CommentBox.tsx
  components/Team/TeamList.tsx
  models/Staff.ts
  package.json
  pages/activity/[name]/index.tsx
  pages/activity/[name]/manage/team.tsx
  pages/activity/[name]/team/[tid].tsx
  pnpm-lock.yaml
Labels: feature

#118 [add] Enrollment Statistic API & page
  components/Activity/ActivityManageFrame.tsx
  components/Activity/EnrollmentStatistic.tsx
  components/PageHead.tsx
  components/ScrollList.tsx
  components/layout/Layout.tsx
  models/Enrollment.ts
  models/Staff.ts
  package.json
  pages/_app.tsx
  pages/activity/[name]/manage/administrator.tsx
  pages/activity/[name]/manage/award.tsx
  pages/activity/[name]/manage/edit.tsx
  pages/activity/[name]/manage/participant.tsx
  pages/activity/[name]/manage/participant/index.tsx
  pages/activity/[name]/manage/participant/statistic.tsx
  pages/activity/[name]/manage/team.tsx
  pages/api/core.ts
  pnpm-lock.yaml
Labels: feature

#114 团队后台/团队报名/团队权限管理/报名/退出/我的团队/其他优化
  components/Activity/ActivityManageFrame.tsx
  components/MainBreadcrumb.tsx
  components/Team/JoinTeamModal.tsx
  components/Team/TeamAdministratorTable.tsx
  components/Team/TeamManageFrame.tsx
  components/Team/TeamParticipantTable.tsx
  components/TeamCreateModal.tsx
  components/User/UserBar.tsx
  models/Activity.ts
  models/Base.ts
  models/Question.ts
  models/Staff.ts
  models/Team.ts
  pages/activity/[name]/index.tsx
  pages/activity/[name]/team/[tid].tsx
  pages/activity/[name]/team/[tid]/index.tsx
  pages/activity/[name]/team/[tid]/manage/participant.tsx
  pages/activity/[name]/team/[tid]/manage/role.tsx
  pages/api/core.ts
Labels: feature

#124 [add] topUserList
  components/User/TopUserAddress.tsx
  components/User/TopUserList.tsx
  models/User.ts
  pages/index.tsx
  styles/TopUserList.module.less
Labels: feature

#129 [fix] topUserList background gap
  pages/index.tsx
Labels: bug

#116 [feature] notice list
  components/Message/ActivityMessageModal.tsx
  components/Message/MessageEditor.tsx
  components/Message/MessageList.tsx
  models/Activity.ts
  models/Message.ts
  pages/activity/[name]/manage/message.tsx
Labels: feature

#133 [feat] activity Organization info
  components/Organization/OrganizationCard.tsx
  components/Organization/OrganizationList.tsx
  pages/activity/[name]/index.tsx
Labels: enhancement

#134 [add] activity dynmaic list
  components/Activity/ActivityLogList.tsx
  components/Message/ActivityMessageModal.tsx
  components/Message/MessageEditor.tsx
  components/Message/MessageList.tsx
  components/Organization/OrganizationList.tsx
  models/Activity.ts
  models/Log.ts
  pages/activity/[name]/index.tsx
  pages/activity/[name]/manage/message.tsx
Labels: feature

#131 [refactor] simplify Activity Edtior components with CSR
  README.md
  components/Activity/ActivityList.tsx
  components/Activity/ActivityManageFrame.tsx
  components/Activity/EnrollmentStatistic.tsx
  components/ActivityAdministratorModal.tsx
  components/ActivityCreate.tsx
  components/ActivityEdit.tsx
  components/ActivityEditor.tsx
  components/AwardList.tsx
  components/FileUpload.tsx
  components/Message/ActivityMessageModal.tsx
  components/Message/MessageList.tsx
  components/Organization/ActivityOrganizationModal.tsx
  components/Organization/OrganizationList.tsx
  components/Team/TeamWorkList.tsx
  components/TeamEditor.tsx
  components/User/TopUserList.tsx
  components/work/WorkEdit.tsx
  models/Activity.ts
  models/Staff.ts
  package.json
  pages/activity/[name]/index.tsx
  pages/activity/[name]/manage/administrator.tsx
  pages/activity/[name]/manage/award.tsx
  pages/activity/[name]/manage/edit.tsx
  pages/activity/[name]/manage/git.tsx
  pages/activity/[name]/manage/message.tsx
  pages/activity/[name]/manage/organization.tsx
  pages/activity/[name]/manage/team.tsx
  pages/activity/[name]/register.tsx
  pages/activity/[name]/team/[tid]/index.tsx
  pages/activity/create.tsx
  pages/index.tsx
  pages/user/[id].tsx
  pnpm-lock.yaml
  public/manifest.json
Labels: feature
