Repository kaiyuanshe/OpenHackathon-Web, pull requests merged in 2023-05, with the labels that each got.

#166 [polish] fix footer en-US translation
  pages/_app.tsx
  translation/en-US.ts
  translation/zh-CN.ts
  translation/zh-TW.ts
Labels: documentation

#167 fix pnpm compatibility with Node.js
  Dockerfile
Labels: bug

#169 [fix]proofread English translation
  components/Activity/ActivityEntry.tsx
  components/Organization/ActivityOrganizationModal.tsx
  translation/en-US.ts
  translation/zh-CN.ts
  translation/zh-TW.ts
Labels: enhancement

#168 [feature] add date time comparison logic
  components/ActivityEditor.tsx
  components/DateTimeInput.tsx
  translation/en-US.ts
  translation/zh-CN.ts
  translation/zh-TW.ts
Labels: enhancement

#171 [add] Azure File model
  components/ActivityEditor.tsx
  components/FileUpload.tsx
  components/HTMLEditor.tsx
  components/work/WorkEdit.tsx
  models/File.ts
  models/Session.ts
  package.json
  pages/_document.tsx
  pages/api/core.ts
  pnpm-lock.yaml
Labels: enhancement
