Repository kaiyuanshe/OpenHackathon-Web, pull requests merged in 2023-06, with the labels that each got.

#174 [optimize] simplify TSX with Advanced components
  components/Activity/ActivityEditor.tsx
  components/Activity/ActivityList.tsx
  components/Activity/ActivityLogList.tsx
  components/Activity/ActivityManageFrame.tsx
  components/Activity/AwardList.tsx
  components/Activity/EnrollmentList.tsx
  components/Git/index.tsx
  components/Message/MessageList.tsx
  components/Organization/OrganizationList.tsx
  components/PlatformAdmin/PlatformAdminFrame.tsx
  components/PlatformAdmin/PlatformAdminList.tsx
  components/Team/TeamAdministratorTable.tsx
  components/Team/TeamAwardAssignment.tsx
  components/Team/TeamAwardCard.tsx
  components/Team/TeamAwardList.tsx
  components/Team/TeamCard.tsx
  components/Team/TeamCreateModal.tsx
  components/Team/TeamEditor.tsx
  components/Team/TeamList.tsx
  components/Team/TeamManageFrame.tsx
  components/Team/TeamMemberList.tsx
  components/Team/TeamParticipantTable.tsx
  components/Team/TeamWork.tsx
  components/Team/TeamWorkList.tsx
  components/Team/WorkEdit.tsx
  components/User/ActivityAdministratorModal.tsx
  components/User/HackathonAdminList.tsx
  components/User/StaffList.tsx
  components/User/UserList.tsx
  components/layout/MainBreadcrumb.tsx
  components/layout/PageHead.tsx
  components/layout/ScrollList.tsx
  models/Translation.ts
  package.json
  pages/_document.tsx
  pages/activity/[name]/index.tsx
  pages/activity/[name]/manage/administrator.tsx
  pages/activity/[name]/manage/award.tsx
  pages/activity/[name]/manage/edit.tsx
  pages/activity/[name]/manage/participant/index.tsx
  pages/activity/[name]/register.tsx
  pages/activity/[name]/team/[tid]/index.tsx
  pages/activity/[name]/team/[tid]/work/[wid]/edit.tsx
  pages/activity/[name]/team/[tid]/work/create.tsx
  pages/activity/create.tsx
  pages/activity/index.tsx
  pages/index.tsx
  pages/user/[id].tsx
  pnpm-lock.yaml
  translation/en-US.ts
  translation/zh-CN.ts
  translation/zh-TW.ts
Labels: enhancement

#173 [feat] Sign up for custom fields
  components/Activity/QuestionnaireCreate.tsx
  components/Activity/QuestionnairePreview.tsx
  components/Activity/QuestionnaireTable.tsx
  configuration/menu.ts
  models/Activity.ts
  models/Question.ts
  pages/activity/[name]/index.tsx
  pages/activity/[name]/manage/participant/index.tsx
  pages/activity/[name]/manage/questionnaire.tsx
  pages/activity/[name]/register.tsx
  translation/en-US.ts
  translation/zh-CN.ts
  translation/zh-TW.ts
Labels: feature

#179 [fix] make only text clickable
  pages/_app.tsx
Labels: bug
