Repository kaiyuanshe/OpenHackathon-Web, pull requests merged in 2024-08, with the labels that each got.

#212 [add] 404 page & Service Status
  components/Activity/ActivityEntry.tsx
  components/Message/MessageList.tsx
  components/NotFoundCard.tsx
  components/Organization/OrganizationList.tsx
  components/Team/TeamWorkList.tsx
  components/User/AuthingGuard.tsx
  components/User/HackathonAdminList.tsx
  next.config.mjs
  package.json
  pages/_app.tsx
  pages/_error.tsx
  pnpm-lock.yaml
  styles/globals.less
  utils/time.ts
Labels: feature

#213 [add] Type package, RESTful API & JWT middleware of OHP back-end v6
  .env
  .env.development
  README.md
  components/Activity/ActivityCard.tsx
  components/Activity/ActivityControl.tsx
  components/Activity/ActivityEditor.tsx
  components/Activity/ActivityEntry.tsx
  components/Activity/ActivityList.tsx
  components/Activity/AwardList.tsx
  components/Activity/EnrollmentList.tsx
  components/Git/Card.tsx
  components/Message/MessageList.tsx
  components/Organization/OrganizationList.tsx
  components/PlatformAdmin/PlatformAdminModal.tsx
  components/Team/TeamAdministratorTable.tsx
  components/Team/TeamAwardCard.tsx
  components/Team/TeamAwardList.tsx
  components/Team/TeamCard.tsx
  components/Team/TeamManageFrame.tsx
  components/Team/TeamParticipantTable.tsx
  components/Team/TeamWorkList.tsx
  components/Team/WorkEditor.tsx
  components/User/ActivityAdministratorModal.tsx
  components/User/TopUserList.tsx
  components/User/UserBar.tsx
  components/User/UserList.tsx
  components/layout/ScrollList.tsx
  models/Activity/Award.ts
  models/Activity/Enrollment.ts
  models/Activity/Log.ts
  models/Activity/Message.ts
  models/Activity/Organization.ts
  models/Activity/Staff.ts
  models/Activity/Team.ts
  models/Activity/index.ts
  models/Base/index.ts
  models/Git.ts
  models/TemplateRepo.ts
  models/User/PlatformAdmin.ts
  models/User/Session.ts
  models/User/index.ts
  next.config.mjs
  package.json
  pages/_app.tsx
  pages/_error.tsx
  pages/activity/[name]/index.tsx
  pages/activity/[name]/manage/administrator.tsx
  pages/activity/[name]/manage/git.tsx
  pages/activity/[name]/manage/message.tsx
  pages/activity/[name]/manage/organization.tsx
  pages/activity/[name]/team/[tid]/index.tsx
  pages/activity/[name]/team/[tid]/manage/git.tsx
  pages/activity/[name]/team/[tid]/manage/participant.tsx
  pages/activity/[name]/team/[tid]/manage/role.tsx
  pages/activity/[name]/team/[tid]/work/[wid]/edit.tsx
  pages/activity/[name]/team/[tid]/work/create.tsx
  pages/activity/create.tsx
  pages/admin/platform-admin.tsx
  pages/api/core.ts
  pnpm-lock.yaml
Labels: enhancement, feature

#214 [refactor] simplify User, Staff, Admin, Log & Enrollment types & models based on Back-end API v6
  .github/workflows/docker.yml
  components/Activity/ActivityLogList.tsx
  components/Activity/ActivityManageFrame.tsx
  components/Activity/EnrollmentList.tsx
  components/Activity/EnrollmentStatistic.tsx
  components/Team/TeamAdministratorTable.tsx
  components/Team/TeamAwardCard.tsx
  components/Team/TeamCard.tsx
  components/Team/TeamManageFrame.tsx
  components/Team/TeamMemberList.tsx
  components/Team/TeamParticipantTable.tsx
  components/User/ActivityAdministratorModal.tsx
  components/User/HackathonAdminList.tsx
  components/User/UserBar.tsx
  components/User/UserList.tsx
  configuration/menu.ts
  models/Activity/Enrollment.ts
  models/Activity/Log.ts
  models/Activity/Staff.ts
  models/Activity/Team.ts
  models/Activity/index.ts
  models/Base/File.ts
  models/Base/index.ts
  models/User/PlatformAdmin.ts
  models/User/Session.ts
  models/User/index.ts
  next.config.mjs
  package.json
  pages/_app.tsx
  pages/activity/[name]/index.tsx
  pages/activity/[name]/manage/participant/index.tsx
  pages/activity/[name]/team/[tid]/index.tsx
  pages/activity/[name]/team/[tid]/manage/git.tsx
  pages/admin/platform-admin.tsx
  pages/api/core.ts
  pages/user/[id].tsx
  pnpm-lock.yaml
  tsconfig.json
Labels: feature

#215 [refactor] simplify Organizer, Team & Team Member types & models based on Back-end v6 API
  .github/workflows/docker.yml
  components/Activity/ActivityLogList.tsx
  components/Organization/ActivityOrganizationModal.tsx
  components/Organization/OrganizationCard.tsx
  components/Organization/OrganizationList.tsx
  components/Team/TeamAdministratorTable.tsx
  components/Team/TeamAwardCard.tsx
  components/Team/TeamAwardList.tsx
  components/Team/TeamCard.tsx
  components/Team/TeamCreateModal.tsx
  components/Team/TeamEditor.tsx
  components/Team/TeamList.tsx
  components/Team/TeamManageFrame.tsx
  components/Team/TeamMemberList.tsx
  components/Team/TeamParticipantTable.tsx
  configuration/menu.ts
  models/Activity/Award.ts
  models/Activity/Log.ts
  models/Activity/Organization.ts
  models/Activity/Team.ts
  models/Activity/index.ts
  package.json
  pages/activity/[name]/index.tsx
  pages/activity/[name]/manage/evaluation.tsx
  pages/activity/[name]/manage/log.tsx
  pages/activity/[name]/manage/team.tsx
  pages/activity/[name]/team/[tid]/index.tsx
  pages/activity/[name]/team/[tid]/manage/participant.tsx
  pages/activity/[name]/team/[tid]/manage/role.tsx
  pnpm-lock.yaml
Labels: enhancement

#216 [refactor] simplify Announcement & Team Work types & models
  .github/pr-badge.yml
  components/Message/MessageList.tsx
  components/Message/MessageModal.tsx
  components/Team/TeamWork.tsx
  components/Team/TeamWorkList.tsx
  configuration/menu.ts
  models/Activity/Message.ts
  models/Activity/Team.ts
  models/Activity/index.ts
  models/Git.ts
  package.json
  pages/activity/[name]/index.tsx
  pages/activity/[name]/manage/announcement.tsx
  pages/activity/[name]/team/[tid]/index.tsx
  pages/activity/[name]/team/[tid]/manage/git.tsx
  pnpm-lock.yaml
Labels: feature

#217 [refactor] simplify types & models of Git Template & Questionnaire based on Back-end v6 API
  Dockerfile
  components/Activity/EnrollmentList.tsx
  components/Activity/EnrollmentStatistic.tsx
  components/Activity/QuestionnaireCreate.tsx
  components/Git/Card.tsx
  components/Git/CardList.tsx
  components/Git/GitTeamCard.tsx
  components/Git/List.tsx
  components/Git/Modal.tsx
  components/Git/TeamGitList.tsx
  components/User/UserBar.tsx
  models/Activity/Enrollment.ts
  models/Activity/Question.ts
  models/Activity/Team.ts
  models/Activity/index.ts
  models/Base/index.ts
  models/Git.ts
  models/TemplateRepo.ts
  models/User/Session.ts
  package.json
  pages/activity/[name]/manage/participant/index.tsx
  pages/activity/[name]/manage/questionnaire.tsx
  pages/activity/[name]/register.tsx
  pages/activity/[name]/team/[tid]/manage/git.tsx
  pages/user/[id].tsx
  pnpm-lock.yaml
  translation/en-US.ts
  translation/zh-CN.ts
  translation/zh-TW.ts
Labels: feature
